# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_scapy_radio_swig', [dirname(__file__)])
        except ImportError:
            import _scapy_radio_swig
            return _scapy_radio_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_scapy_radio_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _scapy_radio_swig = swig_import_helper()
    del swig_import_helper
else:
    import _scapy_radio_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def high_res_timer_now():
  """high_res_timer_now() -> gr::high_res_timer_type"""
  return _scapy_radio_swig.high_res_timer_now()

def high_res_timer_now_perfmon():
  """high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
  return _scapy_radio_swig.high_res_timer_now_perfmon()

def high_res_timer_tps():
  """high_res_timer_tps() -> gr::high_res_timer_type"""
  return _scapy_radio_swig.high_res_timer_tps()

def high_res_timer_epoch():
  """high_res_timer_epoch() -> gr::high_res_timer_type"""
  return _scapy_radio_swig.high_res_timer_epoch()
class add_gr_header(object):
    """<+description of block+>"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def make(*args, **kwargs):
        """
        make(int protocol_id) -> add_gr_header_sptr

        Return a shared_ptr to a new instance of scapy_radio::add_gr_header.

        To avoid accidental use of raw pointers, scapy_radio::add_gr_header's constructor is in a private implementation class. scapy_radio::add_gr_header::make is the public interface for creating new instances.

        Params: (protocol_id)
        """
        return _scapy_radio_swig.add_gr_header_make(*args, **kwargs)

    make = staticmethod(make)
    def protocol_id(self):
        """
        protocol_id(add_gr_header self) -> int

        Params: (NONE)
        """
        return _scapy_radio_swig.add_gr_header_protocol_id(self)

    def set_protocol_id(self, *args, **kwargs):
        """
        set_protocol_id(add_gr_header self, int protocol_id)

        Params: (protocol_id)
        """
        return _scapy_radio_swig.add_gr_header_set_protocol_id(self, *args, **kwargs)

    __swig_destroy__ = _scapy_radio_swig.delete_add_gr_header
    __del__ = lambda self : None;
add_gr_header_swigregister = _scapy_radio_swig.add_gr_header_swigregister
add_gr_header_swigregister(add_gr_header)

def add_gr_header_make(*args, **kwargs):
  """
    add_gr_header_make(int protocol_id) -> add_gr_header_sptr

    Return a shared_ptr to a new instance of scapy_radio::add_gr_header.

    To avoid accidental use of raw pointers, scapy_radio::add_gr_header's constructor is in a private implementation class. scapy_radio::add_gr_header::make is the public interface for creating new instances.

    Params: (protocol_id)
    """
  return _scapy_radio_swig.add_gr_header_make(*args, **kwargs)

class add_gr_header_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::scapy_radio::add_gr_header)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::scapy_radio::add_gr_header)> self) -> add_gr_header_sptr
        __init__(boost::shared_ptr<(gr::scapy_radio::add_gr_header)> self, add_gr_header p) -> add_gr_header_sptr
        """
        this = _scapy_radio_swig.new_add_gr_header_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(add_gr_header_sptr self) -> add_gr_header"""
        return _scapy_radio_swig.add_gr_header_sptr___deref__(self)

    __swig_destroy__ = _scapy_radio_swig.delete_add_gr_header_sptr
    __del__ = lambda self : None;
    def make(self, *args, **kwargs):
        """
        make(add_gr_header_sptr self, int protocol_id) -> add_gr_header_sptr

        Return a shared_ptr to a new instance of scapy_radio::add_gr_header.

        To avoid accidental use of raw pointers, scapy_radio::add_gr_header's constructor is in a private implementation class. scapy_radio::add_gr_header::make is the public interface for creating new instances.

        Params: (protocol_id)
        """
        return _scapy_radio_swig.add_gr_header_sptr_make(self, *args, **kwargs)

    def protocol_id(self):
        """
        protocol_id(add_gr_header_sptr self) -> int

        Params: (NONE)
        """
        return _scapy_radio_swig.add_gr_header_sptr_protocol_id(self)

    def set_protocol_id(self, *args, **kwargs):
        """
        set_protocol_id(add_gr_header_sptr self, int protocol_id)

        Params: (protocol_id)
        """
        return _scapy_radio_swig.add_gr_header_sptr_set_protocol_id(self, *args, **kwargs)

    def history(self):
        """history(add_gr_header_sptr self) -> unsigned int"""
        return _scapy_radio_swig.add_gr_header_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(add_gr_header_sptr self, int which, int delay)
        declare_sample_delay(add_gr_header_sptr self, unsigned int delay)
        """
        return _scapy_radio_swig.add_gr_header_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(add_gr_header_sptr self, int which) -> unsigned int"""
        return _scapy_radio_swig.add_gr_header_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(add_gr_header_sptr self) -> int"""
        return _scapy_radio_swig.add_gr_header_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(add_gr_header_sptr self) -> double"""
        return _scapy_radio_swig.add_gr_header_sptr_relative_rate(self)

    def start(self):
        """start(add_gr_header_sptr self) -> bool"""
        return _scapy_radio_swig.add_gr_header_sptr_start(self)

    def stop(self):
        """stop(add_gr_header_sptr self) -> bool"""
        return _scapy_radio_swig.add_gr_header_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(add_gr_header_sptr self, unsigned int which_input) -> uint64_t"""
        return _scapy_radio_swig.add_gr_header_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(add_gr_header_sptr self, unsigned int which_output) -> uint64_t"""
        return _scapy_radio_swig.add_gr_header_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(add_gr_header_sptr self) -> int"""
        return _scapy_radio_swig.add_gr_header_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(add_gr_header_sptr self, int m)"""
        return _scapy_radio_swig.add_gr_header_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(add_gr_header_sptr self)"""
        return _scapy_radio_swig.add_gr_header_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(add_gr_header_sptr self) -> bool"""
        return _scapy_radio_swig.add_gr_header_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(add_gr_header_sptr self, int m)"""
        return _scapy_radio_swig.add_gr_header_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(add_gr_header_sptr self) -> int"""
        return _scapy_radio_swig.add_gr_header_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(add_gr_header_sptr self, int i) -> long"""
        return _scapy_radio_swig.add_gr_header_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(add_gr_header_sptr self, long max_output_buffer)
        set_max_output_buffer(add_gr_header_sptr self, int port, long max_output_buffer)
        """
        return _scapy_radio_swig.add_gr_header_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(add_gr_header_sptr self, int i) -> long"""
        return _scapy_radio_swig.add_gr_header_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(add_gr_header_sptr self, long min_output_buffer)
        set_min_output_buffer(add_gr_header_sptr self, int port, long min_output_buffer)
        """
        return _scapy_radio_swig.add_gr_header_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(add_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.add_gr_header_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(add_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.add_gr_header_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(add_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.add_gr_header_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(add_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.add_gr_header_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(add_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.add_gr_header_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(add_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.add_gr_header_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(add_gr_header_sptr self, int which) -> float
        pc_input_buffers_full(add_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.add_gr_header_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(add_gr_header_sptr self, int which) -> float
        pc_input_buffers_full_avg(add_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.add_gr_header_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(add_gr_header_sptr self, int which) -> float
        pc_input_buffers_full_var(add_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.add_gr_header_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(add_gr_header_sptr self, int which) -> float
        pc_output_buffers_full(add_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.add_gr_header_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(add_gr_header_sptr self, int which) -> float
        pc_output_buffers_full_avg(add_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.add_gr_header_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(add_gr_header_sptr self, int which) -> float
        pc_output_buffers_full_var(add_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.add_gr_header_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(add_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.add_gr_header_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(add_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.add_gr_header_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(add_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.add_gr_header_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(add_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.add_gr_header_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(add_gr_header_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _scapy_radio_swig.add_gr_header_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(add_gr_header_sptr self)"""
        return _scapy_radio_swig.add_gr_header_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(add_gr_header_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _scapy_radio_swig.add_gr_header_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(add_gr_header_sptr self) -> int"""
        return _scapy_radio_swig.add_gr_header_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(add_gr_header_sptr self) -> int"""
        return _scapy_radio_swig.add_gr_header_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(add_gr_header_sptr self, int priority) -> int"""
        return _scapy_radio_swig.add_gr_header_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(add_gr_header_sptr self) -> std::string"""
        return _scapy_radio_swig.add_gr_header_sptr_name(self)

    def symbol_name(self):
        """symbol_name(add_gr_header_sptr self) -> std::string"""
        return _scapy_radio_swig.add_gr_header_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(add_gr_header_sptr self) -> io_signature_sptr"""
        return _scapy_radio_swig.add_gr_header_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(add_gr_header_sptr self) -> io_signature_sptr"""
        return _scapy_radio_swig.add_gr_header_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(add_gr_header_sptr self) -> long"""
        return _scapy_radio_swig.add_gr_header_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(add_gr_header_sptr self) -> basic_block_sptr"""
        return _scapy_radio_swig.add_gr_header_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(add_gr_header_sptr self, int ninputs, int noutputs) -> bool"""
        return _scapy_radio_swig.add_gr_header_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(add_gr_header_sptr self) -> std::string"""
        return _scapy_radio_swig.add_gr_header_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(add_gr_header_sptr self, std::string name)"""
        return _scapy_radio_swig.add_gr_header_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(add_gr_header_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _scapy_radio_swig.add_gr_header_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(add_gr_header_sptr self) -> swig_int_ptr"""
        return _scapy_radio_swig.add_gr_header_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(add_gr_header_sptr self) -> swig_int_ptr"""
        return _scapy_radio_swig.add_gr_header_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(add_gr_header_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _scapy_radio_swig.add_gr_header_sptr_message_subscribers(self, *args, **kwargs)

add_gr_header_sptr_swigregister = _scapy_radio_swig.add_gr_header_sptr_swigregister
add_gr_header_sptr_swigregister(add_gr_header_sptr)

add_gr_header_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
add_gr_header = add_gr_header.make;

class strip_gr_header(object):
    """<+description of block+>"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def make(*args, **kwargs):
        """
        make(int protocol_id) -> strip_gr_header_sptr

        Return a shared_ptr to a new instance of scapy_radio::strip_gr_header.

        To avoid accidental use of raw pointers, scapy_radio::strip_gr_header's constructor is in a private implementation class. scapy_radio::strip_gr_header::make is the public interface for creating new instances.

        Params: (protocol_id)
        """
        return _scapy_radio_swig.strip_gr_header_make(*args, **kwargs)

    make = staticmethod(make)
    def protocol_id(self):
        """
        protocol_id(strip_gr_header self) -> int

        Params: (NONE)
        """
        return _scapy_radio_swig.strip_gr_header_protocol_id(self)

    def set_protocol_id(self, *args, **kwargs):
        """
        set_protocol_id(strip_gr_header self, int protocol_id)

        Params: (protocol_id)
        """
        return _scapy_radio_swig.strip_gr_header_set_protocol_id(self, *args, **kwargs)

    __swig_destroy__ = _scapy_radio_swig.delete_strip_gr_header
    __del__ = lambda self : None;
strip_gr_header_swigregister = _scapy_radio_swig.strip_gr_header_swigregister
strip_gr_header_swigregister(strip_gr_header)

def strip_gr_header_make(*args, **kwargs):
  """
    strip_gr_header_make(int protocol_id) -> strip_gr_header_sptr

    Return a shared_ptr to a new instance of scapy_radio::strip_gr_header.

    To avoid accidental use of raw pointers, scapy_radio::strip_gr_header's constructor is in a private implementation class. scapy_radio::strip_gr_header::make is the public interface for creating new instances.

    Params: (protocol_id)
    """
  return _scapy_radio_swig.strip_gr_header_make(*args, **kwargs)

class strip_gr_header_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::scapy_radio::strip_gr_header)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::scapy_radio::strip_gr_header)> self) -> strip_gr_header_sptr
        __init__(boost::shared_ptr<(gr::scapy_radio::strip_gr_header)> self, strip_gr_header p) -> strip_gr_header_sptr
        """
        this = _scapy_radio_swig.new_strip_gr_header_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(strip_gr_header_sptr self) -> strip_gr_header"""
        return _scapy_radio_swig.strip_gr_header_sptr___deref__(self)

    __swig_destroy__ = _scapy_radio_swig.delete_strip_gr_header_sptr
    __del__ = lambda self : None;
    def make(self, *args, **kwargs):
        """
        make(strip_gr_header_sptr self, int protocol_id) -> strip_gr_header_sptr

        Return a shared_ptr to a new instance of scapy_radio::strip_gr_header.

        To avoid accidental use of raw pointers, scapy_radio::strip_gr_header's constructor is in a private implementation class. scapy_radio::strip_gr_header::make is the public interface for creating new instances.

        Params: (protocol_id)
        """
        return _scapy_radio_swig.strip_gr_header_sptr_make(self, *args, **kwargs)

    def protocol_id(self):
        """
        protocol_id(strip_gr_header_sptr self) -> int

        Params: (NONE)
        """
        return _scapy_radio_swig.strip_gr_header_sptr_protocol_id(self)

    def set_protocol_id(self, *args, **kwargs):
        """
        set_protocol_id(strip_gr_header_sptr self, int protocol_id)

        Params: (protocol_id)
        """
        return _scapy_radio_swig.strip_gr_header_sptr_set_protocol_id(self, *args, **kwargs)

    def history(self):
        """history(strip_gr_header_sptr self) -> unsigned int"""
        return _scapy_radio_swig.strip_gr_header_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(strip_gr_header_sptr self, int which, int delay)
        declare_sample_delay(strip_gr_header_sptr self, unsigned int delay)
        """
        return _scapy_radio_swig.strip_gr_header_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(strip_gr_header_sptr self, int which) -> unsigned int"""
        return _scapy_radio_swig.strip_gr_header_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(strip_gr_header_sptr self) -> int"""
        return _scapy_radio_swig.strip_gr_header_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(strip_gr_header_sptr self) -> double"""
        return _scapy_radio_swig.strip_gr_header_sptr_relative_rate(self)

    def start(self):
        """start(strip_gr_header_sptr self) -> bool"""
        return _scapy_radio_swig.strip_gr_header_sptr_start(self)

    def stop(self):
        """stop(strip_gr_header_sptr self) -> bool"""
        return _scapy_radio_swig.strip_gr_header_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(strip_gr_header_sptr self, unsigned int which_input) -> uint64_t"""
        return _scapy_radio_swig.strip_gr_header_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(strip_gr_header_sptr self, unsigned int which_output) -> uint64_t"""
        return _scapy_radio_swig.strip_gr_header_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(strip_gr_header_sptr self) -> int"""
        return _scapy_radio_swig.strip_gr_header_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(strip_gr_header_sptr self, int m)"""
        return _scapy_radio_swig.strip_gr_header_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(strip_gr_header_sptr self)"""
        return _scapy_radio_swig.strip_gr_header_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(strip_gr_header_sptr self) -> bool"""
        return _scapy_radio_swig.strip_gr_header_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(strip_gr_header_sptr self, int m)"""
        return _scapy_radio_swig.strip_gr_header_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(strip_gr_header_sptr self) -> int"""
        return _scapy_radio_swig.strip_gr_header_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(strip_gr_header_sptr self, int i) -> long"""
        return _scapy_radio_swig.strip_gr_header_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(strip_gr_header_sptr self, long max_output_buffer)
        set_max_output_buffer(strip_gr_header_sptr self, int port, long max_output_buffer)
        """
        return _scapy_radio_swig.strip_gr_header_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(strip_gr_header_sptr self, int i) -> long"""
        return _scapy_radio_swig.strip_gr_header_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(strip_gr_header_sptr self, long min_output_buffer)
        set_min_output_buffer(strip_gr_header_sptr self, int port, long min_output_buffer)
        """
        return _scapy_radio_swig.strip_gr_header_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(strip_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.strip_gr_header_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(strip_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.strip_gr_header_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(strip_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.strip_gr_header_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(strip_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.strip_gr_header_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(strip_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.strip_gr_header_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(strip_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.strip_gr_header_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(strip_gr_header_sptr self, int which) -> float
        pc_input_buffers_full(strip_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.strip_gr_header_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(strip_gr_header_sptr self, int which) -> float
        pc_input_buffers_full_avg(strip_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.strip_gr_header_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(strip_gr_header_sptr self, int which) -> float
        pc_input_buffers_full_var(strip_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.strip_gr_header_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(strip_gr_header_sptr self, int which) -> float
        pc_output_buffers_full(strip_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.strip_gr_header_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(strip_gr_header_sptr self, int which) -> float
        pc_output_buffers_full_avg(strip_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.strip_gr_header_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(strip_gr_header_sptr self, int which) -> float
        pc_output_buffers_full_var(strip_gr_header_sptr self) -> pmt_vector_float
        """
        return _scapy_radio_swig.strip_gr_header_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(strip_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.strip_gr_header_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(strip_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.strip_gr_header_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(strip_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.strip_gr_header_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(strip_gr_header_sptr self) -> float"""
        return _scapy_radio_swig.strip_gr_header_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(strip_gr_header_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _scapy_radio_swig.strip_gr_header_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(strip_gr_header_sptr self)"""
        return _scapy_radio_swig.strip_gr_header_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(strip_gr_header_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _scapy_radio_swig.strip_gr_header_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(strip_gr_header_sptr self) -> int"""
        return _scapy_radio_swig.strip_gr_header_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(strip_gr_header_sptr self) -> int"""
        return _scapy_radio_swig.strip_gr_header_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(strip_gr_header_sptr self, int priority) -> int"""
        return _scapy_radio_swig.strip_gr_header_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(strip_gr_header_sptr self) -> std::string"""
        return _scapy_radio_swig.strip_gr_header_sptr_name(self)

    def symbol_name(self):
        """symbol_name(strip_gr_header_sptr self) -> std::string"""
        return _scapy_radio_swig.strip_gr_header_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(strip_gr_header_sptr self) -> io_signature_sptr"""
        return _scapy_radio_swig.strip_gr_header_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(strip_gr_header_sptr self) -> io_signature_sptr"""
        return _scapy_radio_swig.strip_gr_header_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(strip_gr_header_sptr self) -> long"""
        return _scapy_radio_swig.strip_gr_header_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(strip_gr_header_sptr self) -> basic_block_sptr"""
        return _scapy_radio_swig.strip_gr_header_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(strip_gr_header_sptr self, int ninputs, int noutputs) -> bool"""
        return _scapy_radio_swig.strip_gr_header_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(strip_gr_header_sptr self) -> std::string"""
        return _scapy_radio_swig.strip_gr_header_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(strip_gr_header_sptr self, std::string name)"""
        return _scapy_radio_swig.strip_gr_header_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(strip_gr_header_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _scapy_radio_swig.strip_gr_header_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(strip_gr_header_sptr self) -> swig_int_ptr"""
        return _scapy_radio_swig.strip_gr_header_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(strip_gr_header_sptr self) -> swig_int_ptr"""
        return _scapy_radio_swig.strip_gr_header_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(strip_gr_header_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _scapy_radio_swig.strip_gr_header_sptr_message_subscribers(self, *args, **kwargs)

strip_gr_header_sptr_swigregister = _scapy_radio_swig.strip_gr_header_sptr_swigregister
strip_gr_header_sptr_swigregister(strip_gr_header_sptr)

strip_gr_header_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
strip_gr_header = strip_gr_header.make;



