# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_wmbus_swig', [dirname(__file__)])
        except ImportError:
            import _wmbus_swig
            return _wmbus_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_wmbus_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _wmbus_swig = swig_import_helper()
    del swig_import_helper
else:
    import _wmbus_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def high_res_timer_now():
  """high_res_timer_now() -> gr::high_res_timer_type"""
  return _wmbus_swig.high_res_timer_now()

def high_res_timer_now_perfmon():
  """high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
  return _wmbus_swig.high_res_timer_now_perfmon()

def high_res_timer_tps():
  """high_res_timer_tps() -> gr::high_res_timer_type"""
  return _wmbus_swig.high_res_timer_tps()

def high_res_timer_epoch():
  """high_res_timer_epoch() -> gr::high_res_timer_type"""
  return _wmbus_swig.high_res_timer_epoch()
class preamble(object):
    """<+description of block+>"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make():
        """
        make() -> preamble_sptr

        Return a shared_ptr to a new instance of wmbus::preamble.

        To avoid accidental use of raw pointers, wmbus::preamble's constructor is in a private implementation class. wmbus::preamble::make is the public interface for creating new instances.

        Params: (NONE)
        """
        return _wmbus_swig.preamble_make()

    make = staticmethod(make)
    __swig_destroy__ = _wmbus_swig.delete_preamble
    __del__ = lambda self : None;
preamble_swigregister = _wmbus_swig.preamble_swigregister
preamble_swigregister(preamble)

def preamble_make():
  """
    preamble_make() -> preamble_sptr

    Return a shared_ptr to a new instance of wmbus::preamble.

    To avoid accidental use of raw pointers, wmbus::preamble's constructor is in a private implementation class. wmbus::preamble::make is the public interface for creating new instances.

    Params: (NONE)
    """
  return _wmbus_swig.preamble_make()

class preamble_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::wmbus::preamble)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::wmbus::preamble)> self) -> preamble_sptr
        __init__(boost::shared_ptr<(gr::wmbus::preamble)> self, preamble p) -> preamble_sptr
        """
        this = _wmbus_swig.new_preamble_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(preamble_sptr self) -> preamble"""
        return _wmbus_swig.preamble_sptr___deref__(self)

    __swig_destroy__ = _wmbus_swig.delete_preamble_sptr
    __del__ = lambda self : None;
    def make(self):
        """
        make(preamble_sptr self) -> preamble_sptr

        Return a shared_ptr to a new instance of wmbus::preamble.

        To avoid accidental use of raw pointers, wmbus::preamble's constructor is in a private implementation class. wmbus::preamble::make is the public interface for creating new instances.

        Params: (NONE)
        """
        return _wmbus_swig.preamble_sptr_make(self)

    def history(self):
        """history(preamble_sptr self) -> unsigned int"""
        return _wmbus_swig.preamble_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(preamble_sptr self, int which, int delay)
        declare_sample_delay(preamble_sptr self, unsigned int delay)
        """
        return _wmbus_swig.preamble_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(preamble_sptr self, int which) -> unsigned int"""
        return _wmbus_swig.preamble_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(preamble_sptr self) -> int"""
        return _wmbus_swig.preamble_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(preamble_sptr self) -> double"""
        return _wmbus_swig.preamble_sptr_relative_rate(self)

    def start(self):
        """start(preamble_sptr self) -> bool"""
        return _wmbus_swig.preamble_sptr_start(self)

    def stop(self):
        """stop(preamble_sptr self) -> bool"""
        return _wmbus_swig.preamble_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(preamble_sptr self, unsigned int which_input) -> uint64_t"""
        return _wmbus_swig.preamble_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(preamble_sptr self, unsigned int which_output) -> uint64_t"""
        return _wmbus_swig.preamble_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(preamble_sptr self) -> int"""
        return _wmbus_swig.preamble_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(preamble_sptr self, int m)"""
        return _wmbus_swig.preamble_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(preamble_sptr self)"""
        return _wmbus_swig.preamble_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(preamble_sptr self) -> bool"""
        return _wmbus_swig.preamble_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(preamble_sptr self, int m)"""
        return _wmbus_swig.preamble_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(preamble_sptr self) -> int"""
        return _wmbus_swig.preamble_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(preamble_sptr self, int i) -> long"""
        return _wmbus_swig.preamble_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(preamble_sptr self, long max_output_buffer)
        set_max_output_buffer(preamble_sptr self, int port, long max_output_buffer)
        """
        return _wmbus_swig.preamble_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(preamble_sptr self, int i) -> long"""
        return _wmbus_swig.preamble_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(preamble_sptr self, long min_output_buffer)
        set_min_output_buffer(preamble_sptr self, int port, long min_output_buffer)
        """
        return _wmbus_swig.preamble_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(preamble_sptr self) -> float"""
        return _wmbus_swig.preamble_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(preamble_sptr self) -> float"""
        return _wmbus_swig.preamble_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(preamble_sptr self) -> float"""
        return _wmbus_swig.preamble_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(preamble_sptr self) -> float"""
        return _wmbus_swig.preamble_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(preamble_sptr self) -> float"""
        return _wmbus_swig.preamble_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(preamble_sptr self) -> float"""
        return _wmbus_swig.preamble_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(preamble_sptr self, int which) -> float
        pc_input_buffers_full(preamble_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.preamble_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(preamble_sptr self, int which) -> float
        pc_input_buffers_full_avg(preamble_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.preamble_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(preamble_sptr self, int which) -> float
        pc_input_buffers_full_var(preamble_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.preamble_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(preamble_sptr self, int which) -> float
        pc_output_buffers_full(preamble_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.preamble_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(preamble_sptr self, int which) -> float
        pc_output_buffers_full_avg(preamble_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.preamble_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(preamble_sptr self, int which) -> float
        pc_output_buffers_full_var(preamble_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.preamble_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(preamble_sptr self) -> float"""
        return _wmbus_swig.preamble_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(preamble_sptr self) -> float"""
        return _wmbus_swig.preamble_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(preamble_sptr self) -> float"""
        return _wmbus_swig.preamble_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(preamble_sptr self) -> float"""
        return _wmbus_swig.preamble_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(preamble_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _wmbus_swig.preamble_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(preamble_sptr self)"""
        return _wmbus_swig.preamble_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(preamble_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _wmbus_swig.preamble_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(preamble_sptr self) -> int"""
        return _wmbus_swig.preamble_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(preamble_sptr self) -> int"""
        return _wmbus_swig.preamble_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(preamble_sptr self, int priority) -> int"""
        return _wmbus_swig.preamble_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(preamble_sptr self) -> std::string"""
        return _wmbus_swig.preamble_sptr_name(self)

    def symbol_name(self):
        """symbol_name(preamble_sptr self) -> std::string"""
        return _wmbus_swig.preamble_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(preamble_sptr self) -> io_signature_sptr"""
        return _wmbus_swig.preamble_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(preamble_sptr self) -> io_signature_sptr"""
        return _wmbus_swig.preamble_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(preamble_sptr self) -> long"""
        return _wmbus_swig.preamble_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(preamble_sptr self) -> basic_block_sptr"""
        return _wmbus_swig.preamble_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(preamble_sptr self, int ninputs, int noutputs) -> bool"""
        return _wmbus_swig.preamble_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(preamble_sptr self) -> std::string"""
        return _wmbus_swig.preamble_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(preamble_sptr self, std::string name)"""
        return _wmbus_swig.preamble_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(preamble_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _wmbus_swig.preamble_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(preamble_sptr self) -> swig_int_ptr"""
        return _wmbus_swig.preamble_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(preamble_sptr self) -> swig_int_ptr"""
        return _wmbus_swig.preamble_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(preamble_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _wmbus_swig.preamble_sptr_message_subscribers(self, *args, **kwargs)

preamble_sptr_swigregister = _wmbus_swig.preamble_sptr_swigregister
preamble_sptr_swigregister(preamble_sptr)

preamble_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
preamble = preamble.make;

class packet_sink(object):
    """Proxy of C++ gr::wmbus::packet_sink class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make():
        """make() -> packet_sink_sptr"""
        return _wmbus_swig.packet_sink_make()

    make = staticmethod(make)
    __swig_destroy__ = _wmbus_swig.delete_packet_sink
    __del__ = lambda self : None;
packet_sink_swigregister = _wmbus_swig.packet_sink_swigregister
packet_sink_swigregister(packet_sink)

def packet_sink_make():
  """packet_sink_make() -> packet_sink_sptr"""
  return _wmbus_swig.packet_sink_make()

class packet_sink_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::wmbus::packet_sink)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::wmbus::packet_sink)> self) -> packet_sink_sptr
        __init__(boost::shared_ptr<(gr::wmbus::packet_sink)> self, packet_sink p) -> packet_sink_sptr
        """
        this = _wmbus_swig.new_packet_sink_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(packet_sink_sptr self) -> packet_sink"""
        return _wmbus_swig.packet_sink_sptr___deref__(self)

    __swig_destroy__ = _wmbus_swig.delete_packet_sink_sptr
    __del__ = lambda self : None;
    def make(self):
        """make(packet_sink_sptr self) -> packet_sink_sptr"""
        return _wmbus_swig.packet_sink_sptr_make(self)

    def history(self):
        """history(packet_sink_sptr self) -> unsigned int"""
        return _wmbus_swig.packet_sink_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(packet_sink_sptr self, int which, int delay)
        declare_sample_delay(packet_sink_sptr self, unsigned int delay)
        """
        return _wmbus_swig.packet_sink_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(packet_sink_sptr self, int which) -> unsigned int"""
        return _wmbus_swig.packet_sink_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(packet_sink_sptr self) -> int"""
        return _wmbus_swig.packet_sink_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(packet_sink_sptr self) -> double"""
        return _wmbus_swig.packet_sink_sptr_relative_rate(self)

    def start(self):
        """start(packet_sink_sptr self) -> bool"""
        return _wmbus_swig.packet_sink_sptr_start(self)

    def stop(self):
        """stop(packet_sink_sptr self) -> bool"""
        return _wmbus_swig.packet_sink_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(packet_sink_sptr self, unsigned int which_input) -> uint64_t"""
        return _wmbus_swig.packet_sink_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(packet_sink_sptr self, unsigned int which_output) -> uint64_t"""
        return _wmbus_swig.packet_sink_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(packet_sink_sptr self) -> int"""
        return _wmbus_swig.packet_sink_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(packet_sink_sptr self, int m)"""
        return _wmbus_swig.packet_sink_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(packet_sink_sptr self)"""
        return _wmbus_swig.packet_sink_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(packet_sink_sptr self) -> bool"""
        return _wmbus_swig.packet_sink_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(packet_sink_sptr self, int m)"""
        return _wmbus_swig.packet_sink_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(packet_sink_sptr self) -> int"""
        return _wmbus_swig.packet_sink_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(packet_sink_sptr self, int i) -> long"""
        return _wmbus_swig.packet_sink_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(packet_sink_sptr self, long max_output_buffer)
        set_max_output_buffer(packet_sink_sptr self, int port, long max_output_buffer)
        """
        return _wmbus_swig.packet_sink_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(packet_sink_sptr self, int i) -> long"""
        return _wmbus_swig.packet_sink_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(packet_sink_sptr self, long min_output_buffer)
        set_min_output_buffer(packet_sink_sptr self, int port, long min_output_buffer)
        """
        return _wmbus_swig.packet_sink_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(packet_sink_sptr self) -> float"""
        return _wmbus_swig.packet_sink_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(packet_sink_sptr self) -> float"""
        return _wmbus_swig.packet_sink_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(packet_sink_sptr self) -> float"""
        return _wmbus_swig.packet_sink_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(packet_sink_sptr self) -> float"""
        return _wmbus_swig.packet_sink_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(packet_sink_sptr self) -> float"""
        return _wmbus_swig.packet_sink_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(packet_sink_sptr self) -> float"""
        return _wmbus_swig.packet_sink_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(packet_sink_sptr self, int which) -> float
        pc_input_buffers_full(packet_sink_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.packet_sink_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(packet_sink_sptr self, int which) -> float
        pc_input_buffers_full_avg(packet_sink_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.packet_sink_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(packet_sink_sptr self, int which) -> float
        pc_input_buffers_full_var(packet_sink_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.packet_sink_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(packet_sink_sptr self, int which) -> float
        pc_output_buffers_full(packet_sink_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.packet_sink_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(packet_sink_sptr self, int which) -> float
        pc_output_buffers_full_avg(packet_sink_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.packet_sink_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(packet_sink_sptr self, int which) -> float
        pc_output_buffers_full_var(packet_sink_sptr self) -> pmt_vector_float
        """
        return _wmbus_swig.packet_sink_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(packet_sink_sptr self) -> float"""
        return _wmbus_swig.packet_sink_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(packet_sink_sptr self) -> float"""
        return _wmbus_swig.packet_sink_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(packet_sink_sptr self) -> float"""
        return _wmbus_swig.packet_sink_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(packet_sink_sptr self) -> float"""
        return _wmbus_swig.packet_sink_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(packet_sink_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _wmbus_swig.packet_sink_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(packet_sink_sptr self)"""
        return _wmbus_swig.packet_sink_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(packet_sink_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _wmbus_swig.packet_sink_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(packet_sink_sptr self) -> int"""
        return _wmbus_swig.packet_sink_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(packet_sink_sptr self) -> int"""
        return _wmbus_swig.packet_sink_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(packet_sink_sptr self, int priority) -> int"""
        return _wmbus_swig.packet_sink_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(packet_sink_sptr self) -> std::string"""
        return _wmbus_swig.packet_sink_sptr_name(self)

    def symbol_name(self):
        """symbol_name(packet_sink_sptr self) -> std::string"""
        return _wmbus_swig.packet_sink_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(packet_sink_sptr self) -> io_signature_sptr"""
        return _wmbus_swig.packet_sink_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(packet_sink_sptr self) -> io_signature_sptr"""
        return _wmbus_swig.packet_sink_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(packet_sink_sptr self) -> long"""
        return _wmbus_swig.packet_sink_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(packet_sink_sptr self) -> basic_block_sptr"""
        return _wmbus_swig.packet_sink_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(packet_sink_sptr self, int ninputs, int noutputs) -> bool"""
        return _wmbus_swig.packet_sink_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(packet_sink_sptr self) -> std::string"""
        return _wmbus_swig.packet_sink_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(packet_sink_sptr self, std::string name)"""
        return _wmbus_swig.packet_sink_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(packet_sink_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _wmbus_swig.packet_sink_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(packet_sink_sptr self) -> swig_int_ptr"""
        return _wmbus_swig.packet_sink_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(packet_sink_sptr self) -> swig_int_ptr"""
        return _wmbus_swig.packet_sink_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(packet_sink_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _wmbus_swig.packet_sink_sptr_message_subscribers(self, *args, **kwargs)

packet_sink_sptr_swigregister = _wmbus_swig.packet_sink_sptr_swigregister
packet_sink_sptr_swigregister(packet_sink_sptr)

packet_sink_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
packet_sink = packet_sink.make;



